FROM node:lts-alpine3.22

ARG PORT=3000
ARG NAME=Nurfaidzy

RUN apk --no-cache add curl

RUN mkdir app
WORKDIR /app

COPY index.js .
RUN npm init -y && npm install express

EXPOSE ${PORT}

# HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD curl --fail http://localhost:${PORT}/health || exit 1

CMD ["node", "index.js"]